version: '3.8'
services:
  rocket-flask:
    container_name: rocket_flask
    restart: always
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - rocket-flask
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 